CREATE TABLE IF NOT EXISTS `trophy-map`.`domain_property` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `isDefault` TINYINT(1) NOT NULL,
  `item` BIGINT(20) NOT NULL,
  `locale` VARCHAR(255) NULL DEFAULT NULL,
  `type` BIGINT(20) NOT NULL,
  `value` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8